FROM node:18-alpine as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build:dev

FROM abdennour/nginx-distroless-unprivileged as release
WORKDIR /opt/app
COPY --chown=1001:0 ./config /etc/nginx/conf.d
COPY --from=build  --chown=1001:0 /app/dist/. .
EXPOSE 8080
USER 1001